### PR TITLE
Replace `minicose` with `coset`

### LINKED ISSUE #34: Remove minicose and replace with coset

### PR DESCRIPTION
**Pull request by fmorency**
This is a first iteration where `minicose` was nuked and replaced with
`coset`. The code is in a working state, but wasn't refactored nor
DRYed.

There are still some TODO left, as well as more tests to write.

The `to_bytes_stable()` method isn't needed anymore; `coset` serialization is stable.

Fixes #34

### CODE REVIEW

**Comment by fmorency** [comment]
As discussed, this is a "drop-in" replacement for `minicose` This should be merged with https://github.com/l-1-labs/many-framework/pull/61

We can refactor the architecture after.

**Comment by fmorency** [comment]
@hansl I just discovered that all reftests are failing on this branch. I need to investigate.

**Comment by fmorency** [comment]
@hansl It's all fixed now. You can review. Thanks.

**Review by hansl — APPROVED** [review]
Can you ask @tantommy for help checking if this is still compatible with the JavaScript version?

Notably we use stably sorted serialization for CBOR, and that matters for keys (since the identity is a hash of the sorted public key). So if this works with our JavaScript frontend, LGTM.

**Comment by tantommy** [comment]
> Can you ask @tantommy for help checking if this is still compatible with the JavaScript version?
> 
> Notably we use stably sorted serialization for CBOR, and that matters for keys (since the identity is a hash of the sorted public key). So if this works with our JavaScript frontend, LGTM.

everything (create/import accounts, send tokens) is working fine from the frontend.
@fmorency @hansl

**Review by hansl — APPROVED** [review]

**Pull request merged**
